name: Tests
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang

    env:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root
      POSTGRES_DB: default
      POSTGRES_HOST: postgres

      PUBSUB_HOST: pubsub
      PUBSUB_PORT: 8085

    services:
      postgres:
        image: postgres
        ports:
          - 5432/tcp

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: root
          POSTGRES_DB: default
          POSTGRES_HOST: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: Download dependencies
        run: go mod download && apt update && apt install gcc

      - name: Run tests
        run: go test ./...


  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7